#数据库连接信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://39.101.150.201:3306/lymall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    # Redis 服务器地址
    host: 39.101.150.201
    # Redis 端口号
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（若使用负数表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

#-----------------------------------------------------------------------------------------------

#分页插件配置
pagehelper:
  #分页插件 数据库方言
  helper-dialect: mysql
  #参数
  params: count=countSql
  #合理化分页
  reasonable: true
  #支持方法参数
  support-methods-arguments: true

#-----------------------------------------------------------------------------------------------

#mybatis配置
mybatis:
  configuration:
    #开启驼峰命名支持
    map-underscore-to-camel-case: true
    #开启缓存
    cache-enabled: true

#-----------------------------------------------------------------------------------------------