#阿里云OSS配置信息
aliyun:
  ossconfig:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI4GHUQh3RbCWJdsGZmUzK
    accessKeySecret: SxriSg70JCyde8Ql7bHogqGqVSluRO
    bucketName: lymall-ahui