#腾讯云OSS配置信息
tencent:
  config:
    #id
    secretId: AKIDh9JQ6XyVQ5QQ9cRY4JHAQwDBh4hDfIn2
    #key
    secretKey: A4uf2A2rsRluj4AAwKUPIS0JNGmqfLUE
    #bucketName
    bucketName: lymall-ahui-1304796949
    #地域
    regionName: ap-guangzhou
    #访问基础路径
    baseUrl: https://lymall-ahui-1304796949.cos.ap-guangzhou.myqcloud.com